Repository crowdin/crowdin-cli, pull requests merged in 2023-06, with the labels that each got.

#592 docs: reorder command options
  prepare-docs.sh
  src/main/java/com/crowdin/cli/commands/picocli/BranchAddSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/BundleAddSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/DownloadSourcesSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/DownloadSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/GlossaryDownloadSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/GlossaryUploadSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/ListLanguagesSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/ListProjectSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/ListSourcesSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/ListTranslationsSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/PreTranslateSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StatusProofreadingSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StatusSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StatusTranslationSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StringAddSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StringCommentSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StringDeleteSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StringEditSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StringListSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/TaskAddSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/TaskListSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/TmDownloadSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/TmUploadSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/UploadSourcesCommand.java
  src/main/java/com/crowdin/cli/commands/picocli/UploadTranslationsSubcommand.java
  src/main/resources/messages/messages.properties
  website/mantemplates/crowdin-bundle-add.adoc
  website/mantemplates/crowdin-bundle-list.adoc
  website/mantemplates/crowdin-bundle.adoc
  website/mantemplates/crowdin-download-bundle.adoc
  website/mantemplates/crowdin-glossary.adoc
  website/mantemplates/crowdin-string-list.adoc
  website/mantemplates/crowdin-tm.adoc
Labels: Documentation

#595 feat: Option to exclude some languages from the build
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/DownloadAction.java
  src/main/java/com/crowdin/cli/commands/picocli/DownloadSubcommand.java
  src/main/resources/messages/messages.properties
  src/test/java/com/crowdin/cli/commands/actions/CliActionsTest.java
  src/test/java/com/crowdin/cli/commands/actions/DownloadActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/DownloadSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
Labels: New Option

#598 docs: add metadata description for some pages
  website/docs/advanced.md
  website/docs/configuration.md
  website/docs/faq.md
  website/docs/installation.md
Labels: Documentation

#599 docs: add the 'languages_mapping' option documentation
  website/docs/advanced.md
Labels: Documentation

#600 docs: implement search
  website/docusaurus.config.js
  website/package-lock.json
  website/package.json
Labels: Documentation

#602 docs: enhance the 'download sources' command info
  website/mantemplates/crowdin-download-sources.adoc
Labels: Documentation

#580 fix: unix tests on windows
  src/main/java/com/crowdin/cli/commands/functionality/SourcesUtils.java
  src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java
  src/main/java/com/crowdin/cli/utils/Utils.java
  src/test/java/com/crowdin/cli/commands/actions/DownloadSourcesActionTest.java
  src/test/java/com/crowdin/cli/commands/functionality/SourcesUtilsTest.java
  src/test/java/com/crowdin/cli/utils/AssertUtils.java
  src/test/java/com/crowdin/cli/utils/PlaceholderUtilTest.java
Labels: Tests
