Repository crowdin/crowdin-cli, pull requests merged in 2023-10, with the labels that each got.

#649 feat: added support of passing labels to pre translate command
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/PreTranslateAction.java
  src/main/java/com/crowdin/cli/commands/functionality/RequestBuilder.java
  src/main/java/com/crowdin/cli/commands/picocli/PreTranslateSubcommand.java
  src/main/resources/messages/messages.properties
  versions.properties
Labels: enhancement, hacktoberfest, new option

#655 test: add more Unit tests for the Utils class
  src/test/java/com/crowdin/cli/utils/UtilsTest.java
Labels: hacktoberfest, hacktoberfest-accepted

#661 feat: label command
  src/main/java/com/crowdin/cli/client/ClientLabel.java
  src/main/java/com/crowdin/cli/client/Clients.java
  src/main/java/com/crowdin/cli/client/CrowdinClientLabel.java
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/LabelAddAction.java
  src/main/java/com/crowdin/cli/commands/actions/LabelDeleteAction.java
  src/main/java/com/crowdin/cli/commands/actions/LabelListAction.java
  src/main/java/com/crowdin/cli/commands/picocli/ActCommandLabel.java
  src/main/java/com/crowdin/cli/commands/picocli/CommandNames.java
  src/main/java/com/crowdin/cli/commands/picocli/LabelAddSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/LabelDeleteSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/LabelListSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/LabelSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/RootCommand.java
  src/main/resources/messages/messages.properties
  src/test/java/com/crowdin/cli/client/CrowdinClientLabelTest.java
  src/test/java/com/crowdin/cli/commands/actions/CliActionsTest.java
  src/test/java/com/crowdin/cli/commands/actions/LabelAddActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/LabelDeleteActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/LabelListActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/LabelAddSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/LabelDeleteSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/LabelListSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
  src/test/java/com/crowdin/cli/commands/picocli/ScreenshotDeleteSubcommandTest.java
  website/mantemplates/crowdin-label-add.adoc
  website/mantemplates/crowdin-label-delete.adoc
  website/mantemplates/crowdin-label-list.adoc
  website/mantemplates/crowdin-label.adoc
  website/sidebars.js
Labels: enhancement, new command

#662 test: add tests for DistributionReleaseAction
  src/test/java/com/crowdin/cli/commands/actions/DistributionReleaseActionTest.java
Labels: hacktoberfest

#650 docs: xcstrings files section
  website/docs/advanced.md
Labels: documentation

#672 docs: update CI/CD article
  website/docs/ci-cd.md
Labels: documentation

#673 fix: Update dependencies version (#615)
  src/main/java/com/crowdin/cli/utils/Utils.java
  versions.properties
Labels: hacktoberfest, hacktoberfest-accepted

#677 docs: disable trailing slash
  website/docusaurus.config.js
Labels: documentation
