Repository crowdin/crowdin-cli, pull requests merged in 2023-04, with the labels that each got.

#556 docs: fix headings (2)
  .github/workflows/build-test.yml
  prepare-docs.sh
Labels: Documentation

#558 docs: improve the Introduction section
  website/docs/configuration.md
  website/docs/intro.md
Labels: Documentation

#559 docs: extend the CI/CD article
  website/docs/ci-cd.md
Labels: Documentation

#560 docs: add Chocolatey installation info
  website/docs/installation.md
Labels: Documentation

#564 ci: fix the 'bump-version' WF
  .github/workflows/bump-version.yml
Labels: CI/CD

#565 ci: fix chocolatey shasum update
  .github/workflows/bump-version.yml
  .github/workflows/publish.yml
  release.config.js
Labels: CI/CD

#566 ci: distribute the bash completion script
  .github/workflows/build-test.yml
  .github/workflows/publish.yml
  package-lock.json
Labels: CI/CD

#549 feat: add bundle command support into cli
  build.gradle
  src/main/java/com/crowdin/cli/client/ClientBundle.java
  src/main/java/com/crowdin/cli/client/Clients.java
  src/main/java/com/crowdin/cli/client/CrowdinClientBundle.java
  src/main/java/com/crowdin/cli/client/CrowdinClientGlossary.java
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/BundleAddAction.java
  src/main/java/com/crowdin/cli/commands/actions/BundleListAction.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/DownloadBundleAction.java
  src/main/java/com/crowdin/cli/commands/actions/TaskListAction.java
  src/main/java/com/crowdin/cli/commands/functionality/FsFiles.java
  src/main/java/com/crowdin/cli/commands/picocli/ActCommandBundle.java
  src/main/java/com/crowdin/cli/commands/picocli/BundleAddSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/BundleListSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/BundleSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/CommandNames.java
  src/main/java/com/crowdin/cli/commands/picocli/DownloadBundleSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/DownloadSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/DownloadTargetsSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/RootCommand.java
  src/main/java/com/crowdin/cli/utils/console/ExecutionStatus.java
  src/main/resources/messages/messages.properties
  src/test/java/com/crowdin/cli/client/CrowdinClientBundleTest.java
  src/test/java/com/crowdin/cli/commands/actions/BundleAddActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/BundleListActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/DownloadBundleActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/BundleAddSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/BundleListSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
  website/mantemplates/crowdin-bundle-add.adoc
  website/mantemplates/crowdin-bundle-list.adoc
  website/mantemplates/crowdin-bundle.adoc
  website/mantemplates/crowdin-download-bundle.adoc
  website/sidebars.js
Labels: New Command

#569 ci: run test reporter only for the 'cli3' branch
  .github/workflows/build-test.yml
Labels: CI/CD

#576 ci: generate code coverage only on ubuntu-latest
  .github/workflows/build-test.yml
Labels: CI/CD

#575 ci: run tests on windows
  .github/workflows/build-test.yml
  src/test/java/com/crowdin/cli/commands/actions/DownloadSourcesActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/subactions/DeleteObsoleteProjectFilesSubActionTest.java
  src/test/java/com/crowdin/cli/commands/functionality/ProjectFilesUtilsTest.java
  src/test/java/com/crowdin/cli/commands/functionality/SourcesUtilsTest.java
  src/test/java/com/crowdin/cli/commands/functionality/TranslationsUtilsTest.java
  src/test/java/com/crowdin/cli/utils/PlaceholderUtilTest.java
Labels: CI/CD
