Repository crowdin/crowdin-cli, pull requests merged in 2023-09, with the labels that each got.

#630 docs: improve the FAQ section
  website/docs/faq.md
Labels: documentation

#632 docs: add examples of the 'distribution add' command usage
  website/mantemplates/crowdin-distribution-add.adoc
Labels: documentation

#633 docs: separate section for the 'crowdin download translations' subcommand
  website/mantemplates/crowdin-download-translations.adoc
  website/sidebars.js
Labels: documentation

#631 feat: new command: screenshot
  prepare-docs.sh
  src/main/java/com/crowdin/cli/client/AutoTagInProgressException.java
  src/main/java/com/crowdin/cli/client/ClientScreenshot.java
  src/main/java/com/crowdin/cli/client/Clients.java
  src/main/java/com/crowdin/cli/client/CrowdinClientScreenshot.java
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/ScreenshotDeleteAction.java
  src/main/java/com/crowdin/cli/commands/actions/ScreenshotListAction.java
  src/main/java/com/crowdin/cli/commands/actions/ScreenshotUploadAction.java
  src/main/java/com/crowdin/cli/commands/picocli/ActCommandScreenshot.java
  src/main/java/com/crowdin/cli/commands/picocli/CommandNames.java
  src/main/java/com/crowdin/cli/commands/picocli/RootCommand.java
  src/main/java/com/crowdin/cli/commands/picocli/ScreenshotDeleteSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/ScreenshotListSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/ScreenshotSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/ScreenshotUploadSubcommand.java
  src/main/resources/messages/messages.properties
  src/test/java/com/crowdin/cli/client/CrowdinClientScreenshotTest.java
  src/test/java/com/crowdin/cli/commands/actions/CliActionsTest.java
  src/test/java/com/crowdin/cli/commands/actions/ScreenshotDeleteActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/ScreenshotListActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/ScreenshotUploadActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
  src/test/java/com/crowdin/cli/commands/picocli/ScreenshotDeleteSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/ScreenshotListSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/ScreenshotUploadSubcommandTest.java
  website/mantemplates/crowdin-screenshot-delete.adoc
  website/mantemplates/crowdin-screenshot-list.adoc
  website/mantemplates/crowdin-screenshot-upload.adoc
  website/mantemplates/crowdin-screenshot.adoc
  website/sidebars.js
Labels: enhancement, new command

#634 feat: task add command - add '--include-pre-translated-strings-only' option
  prepare-docs.sh
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/TaskAddAction.java
  src/main/java/com/crowdin/cli/commands/functionality/RequestBuilder.java
  src/main/java/com/crowdin/cli/commands/picocli/TaskAddSubcommand.java
  src/main/resources/messages/messages.properties
  src/test/java/com/crowdin/cli/commands/actions/TaskAddActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
Labels: enhancement, new option

#636 docs: fix command synopsis
  src/main/resources/messages/messages.properties
Labels: documentation

#637 ci: fix chocolatey nuspec
  chocolatey/crowdin-cli.nuspec
Labels: CI/CD

#638 docs: add release notes link to header
  website/docusaurus.config.js
Labels: documentation

#643 fix: translations download without preserve hierarchy
  src/main/java/com/crowdin/cli/commands/actions/DownloadAction.java
  src/test/java/com/crowdin/cli/commands/actions/DownloadActionTest.java
Labels: bug
