Repository crowdin/crowdin-cli, pull requests merged in 2023-05, with the labels that each got.

#581 docs: add Nix package manager installation instruction
  website/docs/installation.md
Labels: Documentation

#583 ci: trying to fix the homebrew workflow dispatch
  .github/workflows/publish.yml
Labels: CI/CD

#588 feat: New command: comment
  src/main/java/com/crowdin/cli/client/ClientComment.java
  src/main/java/com/crowdin/cli/client/Clients.java
  src/main/java/com/crowdin/cli/client/CrowdinClientComment.java
  src/main/java/com/crowdin/cli/client/CrowdinClientCore.java
  src/main/java/com/crowdin/cli/client/CrowdinProjectClient.java
  src/main/java/com/crowdin/cli/client/ProjectClient.java
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/CommentListAction.java
  src/main/java/com/crowdin/cli/commands/actions/CommentResolveAction.java
  src/main/java/com/crowdin/cli/commands/actions/StringCommentAction.java
  src/main/java/com/crowdin/cli/commands/functionality/RequestBuilder.java
  src/main/java/com/crowdin/cli/commands/picocli/ActCommandComment.java
  src/main/java/com/crowdin/cli/commands/picocli/CommandNames.java
  src/main/java/com/crowdin/cli/commands/picocli/CommentListSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/CommentResolveSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/CommentSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/RootCommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StringCommentSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/StringSubcommand.java
  src/main/resources/messages/messages.properties
  src/test/java/com/crowdin/cli/client/CrowdinClientCommentTest.java
  src/test/java/com/crowdin/cli/commands/actions/CommentListActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/CommentResolveActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/StringCommentActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/CommentListSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/CommentResolveSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
  src/test/java/com/crowdin/cli/commands/picocli/StringCommentSubcommandTest.java
  website/mantemplates/crowdin-comment-list.adoc
  website/mantemplates/crowdin-comment-resolve.adoc
  website/mantemplates/crowdin-comment.adoc
  website/mantemplates/crowdin-string-comment.adoc
  website/sidebars.js
Labels: New Command

#589 docs: enhance the FAQ section
  website/docs/faq.md
Labels: Documentation
