Repository crowdin/crowdin-cli, pull requests merged in 2024-02, with the labels that each got.

#720 docs: update the Files Management article
  website/docs/tutorials/files-management.md
Labels: documentation

#721 feat: label option for screenshot upload command
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/ScreenshotUploadAction.java
  src/main/java/com/crowdin/cli/commands/picocli/ScreenshotUploadSubcommand.java
  src/test/java/com/crowdin/cli/commands/actions/CliActionsTest.java
  src/test/java/com/crowdin/cli/commands/actions/ScreenshotUploadActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
Labels: enhancement, new option

#722 feat: label option for string list command
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/StringListAction.java
  src/main/java/com/crowdin/cli/commands/picocli/StringListSubcommand.java
  src/test/java/com/crowdin/cli/commands/actions/CliActionsTest.java
  src/test/java/com/crowdin/cli/commands/actions/StringListActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
  src/test/java/com/crowdin/cli/commands/picocli/StringListSubcommandTest.java
Labels: enhancement, new option

#727 build: update dependencies
  .github/workflows/build-test.yml
  .github/workflows/bump-version.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docs-release.yml
  .github/workflows/publish.yml
  package-lock.json
  package.json
Labels: dependencies

#725 feat: multilingual option
  src/main/java/com/crowdin/cli/properties/FileBean.java
  src/main/java/com/crowdin/cli/properties/PropertiesBuilder.java
  src/test/java/com/crowdin/cli/commands/functionality/PropertiesBuilderTest.java
  website/docs/advanced.md
Labels: enhancement
