Repository crowdin/crowdin-cli, pull requests merged in 2024-01, with the labels that each got.

#690 chore: remove unused glassfish.jersey deps
  build.gradle
  versions.properties
Labels: dependencies

#691 chore: fix vulnerabilities in direct dependencies
  versions.properties
Labels: dependencies

#692 build(deps): drop unused json-patch dependency
  build.gradle
  src/test/java/com/crowdin/cli/commands/picocli/UploadTranslationsSubcommandTest.java
  versions.properties
Labels: dependencies

#694 build: remove checkstyle
  build.gradle
  config/checkstyle/checkstyle.xml
Labels: dependencies

#697 ci: improve workflows
  .github/workflows/build-test.yml
  .github/workflows/bump-version.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docs-release.yml
  .github/workflows/lint-pr-title.yml
  .github/workflows/publish.yml
  website/docs/ci-cd.md
Labels: CI/CD

#698 docs: update badges and installation guide
  README.md
  website/docs/installation.md
  website/docs/intro.md
Labels: documentation

#699 ci: fix chocolatey publishing
  .github/workflows/publish.yml
  packages/chocolatey/crowdin-cli.nuspec
Labels: CI/CD

#702 ci: fix zip package structure
  .github/workflows/publish.yml
Labels: CI/CD

#703 ci: install local chocolatey package before publishing
  .github/workflows/publish.yml
Labels: CI/CD

#684 fix: windows escape symbols
  src/main/java/com/crowdin/cli/commands/actions/DownloadSourcesAction.java
  src/main/java/com/crowdin/cli/commands/actions/ScreenshotUploadAction.java
  src/main/java/com/crowdin/cli/commands/actions/StatusAction.java
  src/main/java/com/crowdin/cli/commands/functionality/SourcesUtils.java
  src/main/java/com/crowdin/cli/utils/PlaceholderUtil.java
  src/main/java/com/crowdin/cli/utils/Utils.java
  src/test/java/com/crowdin/cli/commands/functionality/SourcesUtilsTest.java
  src/test/java/com/crowdin/cli/utils/UtilsTest.java
Labels: bug, windows

#711 docs: update zip package Readme
  packages/zip/README.txt
Labels: documentation

#708 feat: file command
  prepare-docs.sh
  src/main/java/com/crowdin/cli/client/CrowdinClientLabel.java
  src/main/java/com/crowdin/cli/client/CrowdinClientTask.java
  src/main/java/com/crowdin/cli/client/CrowdinClientTm.java
  src/main/java/com/crowdin/cli/client/CrowdinProjectClient.java
  src/main/java/com/crowdin/cli/client/CrowdinProjectInfo.java
  src/main/java/com/crowdin/cli/client/ProjectClient.java
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/DownloadAction.java
  src/main/java/com/crowdin/cli/commands/actions/FileDeleteAction.java
  src/main/java/com/crowdin/cli/commands/actions/FileDownloadAction.java
  src/main/java/com/crowdin/cli/commands/actions/FileDownloadTranslationAction.java
  src/main/java/com/crowdin/cli/commands/actions/FileUploadAction.java
  src/main/java/com/crowdin/cli/commands/actions/FileUploadTranslationAction.java
  src/main/java/com/crowdin/cli/commands/actions/TaskAddAction.java
  src/main/java/com/crowdin/cli/commands/actions/UploadSourcesAction.java
  src/main/java/com/crowdin/cli/commands/functionality/BranchUtils.java
  src/main/java/com/crowdin/cli/commands/functionality/RequestBuilder.java
  src/main/java/com/crowdin/cli/commands/picocli/CommandNames.java
  src/main/java/com/crowdin/cli/commands/picocli/FileDeleteSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/FileDownloadSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/FileSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/FileUploadSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/RootCommand.java
  src/main/resources/messages/messages.properties
  src/test/java/com/crowdin/cli/client/CrowdinClientTaskTest.java
  src/test/java/com/crowdin/cli/commands/actions/CliActionsTest.java
  src/test/java/com/crowdin/cli/commands/actions/FileDeleteActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/FileDownloadActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/FileDownloadTranslationActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/FileUploadActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/FileUploadTranslationActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/TaskAddActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/DownloadSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/FileDeleteSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/FileDownloadSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/FileUploadSubcommandTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
  versions.properties
  website/mantemplates/crowdin-file-delete.adoc
  website/mantemplates/crowdin-file-download.adoc
  website/mantemplates/crowdin-file-upload.adoc
  website/mantemplates/crowdin-file.adoc
  website/sidebars.js
Labels: enhancement, new command

#712 docs: Files management article
  website/docs/tutorials/files-management.md
  website/sidebars.js
Labels: documentation
