Repository crowdin/crowdin-cli, pull requests merged in 2025-02, with the labels that each got.

#895 chore(build): update npm dependencies
  .github/workflows/build-test.yml
  .github/workflows/publish.yml
  package-lock.json
  package.json
Labels: dependencies

#896 docs: configuration improvements
  website/docs/configuration.md
Labels: documentation

#897 feat: distribution edit command
  src/main/java/com/crowdin/cli/client/ClientDistribution.java
  src/main/java/com/crowdin/cli/client/CrowdinClientDistribution.java
  src/main/java/com/crowdin/cli/commands/Actions.java
  src/main/java/com/crowdin/cli/commands/actions/CliActions.java
  src/main/java/com/crowdin/cli/commands/actions/DistributionAddAction.java
  src/main/java/com/crowdin/cli/commands/actions/DistributionEditAction.java
  src/main/java/com/crowdin/cli/commands/actions/DistributionReleaseAction.java
  src/main/java/com/crowdin/cli/commands/picocli/DistributionEditSubcommand.java
  src/main/java/com/crowdin/cli/commands/picocli/DistributionSubcommand.java
  src/main/resources/messages/messages.properties
  src/test/java/com/crowdin/cli/client/CrowdinClientDistributionTest.java
  src/test/java/com/crowdin/cli/commands/actions/CliActionsTest.java
  src/test/java/com/crowdin/cli/commands/actions/DistributionAddActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/DistributionEditActionTest.java
  src/test/java/com/crowdin/cli/commands/actions/DistributionReleaseActionTest.java
  src/test/java/com/crowdin/cli/commands/picocli/PicocliTestUtils.java
  website/mantemplates/crowdin-distribution-edit.adoc
  website/sidebars.js
Labels: new command
